---
abstract: 'Creates the mirror.yml and mirror.json files'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: CPAN::Indexer::Mirror
name: CPAN-Indexer-Mirror
no_index:
  directory:
    - inc
    - t
requires:
  File::Remove: 1.42
  File::Spec: 0.80
  JSON: 2.00
  Parse::CPAN::MirroredBy: 0.01
  URI: 1.34
  YAML::Tiny: 1.32
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
